// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRansomwareUltraLegacy returns the embedded CollectionSpec for ransomwareUltraLegacy.
func loadRansomwareUltraLegacy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RansomwareUltraLegacyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ransomwareUltraLegacy: %w", err)
	}

	return spec, err
}

// loadRansomwareUltraLegacyObjects loads ransomwareUltraLegacy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ransomwareUltraLegacyObjects
//	*ransomwareUltraLegacyPrograms
//	*ransomwareUltraLegacyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRansomwareUltraLegacyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRansomwareUltraLegacy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ransomwareUltraLegacySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ransomwareUltraLegacySpecs struct {
	ransomwareUltraLegacyProgramSpecs
	ransomwareUltraLegacyMapSpecs
}

// ransomwareUltraLegacySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ransomwareUltraLegacyProgramSpecs struct {
	KpOverrideExecve    *ebpf.ProgramSpec `ebpf:"kp_override_execve"`
	KpOverrideFtruncate *ebpf.ProgramSpec `ebpf:"kp_override_ftruncate"`
	KpOverrideLink      *ebpf.ProgramSpec `ebpf:"kp_override_link"`
	KpOverrideOpen      *ebpf.ProgramSpec `ebpf:"kp_override_open"`
	KpOverrideOpenat    *ebpf.ProgramSpec `ebpf:"kp_override_openat"`
	KpOverridePwrite64  *ebpf.ProgramSpec `ebpf:"kp_override_pwrite64"`
	KpOverrideRename    *ebpf.ProgramSpec `ebpf:"kp_override_rename"`
	KpOverrideSymlink   *ebpf.ProgramSpec `ebpf:"kp_override_symlink"`
	KpOverrideTruncate  *ebpf.ProgramSpec `ebpf:"kp_override_truncate"`
	KpOverrideUnlink    *ebpf.ProgramSpec `ebpf:"kp_override_unlink"`
	KpOverrideWrite     *ebpf.ProgramSpec `ebpf:"kp_override_write"`
	KpOverrideWritev    *ebpf.ProgramSpec `ebpf:"kp_override_writev"`
	KpRetOpen           *ebpf.ProgramSpec `ebpf:"kp_ret_open"`
	KpRetOpenat         *ebpf.ProgramSpec `ebpf:"kp_ret_openat"`
}

// ransomwareUltraLegacyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ransomwareUltraLegacyMapSpecs struct {
	AllowedCgroups     *ebpf.MapSpec `ebpf:"allowed_cgroups"`
	BlockedTgids       *ebpf.MapSpec `ebpf:"blocked_tgids"`
	CgroupScopeEnabled *ebpf.MapSpec `ebpf:"cgroup_scope_enabled"`
	EventCursor        *ebpf.MapSpec `ebpf:"event_cursor"`
	Events             *ebpf.MapSpec `ebpf:"events"`
	IocExtensions      *ebpf.MapSpec `ebpf:"ioc_extensions"`
	IocRansomNotes     *ebpf.MapSpec `ebpf:"ioc_ransom_notes"`
	PendingOpens       *ebpf.MapSpec `ebpf:"pending_opens"`
	ProtectedDirs      *ebpf.MapSpec `ebpf:"protected_dirs"`
	RingbufDrops       *ebpf.MapSpec `ebpf:"ringbuf_drops"`
	ScratchEvents      *ebpf.MapSpec `ebpf:"scratch_events"`
}

// ransomwareUltraLegacyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRansomwareUltraLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ransomwareUltraLegacyObjects struct {
	ransomwareUltraLegacyPrograms
	ransomwareUltraLegacyMaps
}

func (o *ransomwareUltraLegacyObjects) Close() error {
	return _RansomwareUltraLegacyClose(
		&o.ransomwareUltraLegacyPrograms,
		&o.ransomwareUltraLegacyMaps,
	)
}

// ransomwareUltraLegacyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRansomwareUltraLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ransomwareUltraLegacyMaps struct {
	AllowedCgroups     *ebpf.Map `ebpf:"allowed_cgroups"`
	BlockedTgids       *ebpf.Map `ebpf:"blocked_tgids"`
	CgroupScopeEnabled *ebpf.Map `ebpf:"cgroup_scope_enabled"`
	EventCursor        *ebpf.Map `ebpf:"event_cursor"`
	Events             *ebpf.Map `ebpf:"events"`
	IocExtensions      *ebpf.Map `ebpf:"ioc_extensions"`
	IocRansomNotes     *ebpf.Map `ebpf:"ioc_ransom_notes"`
	PendingOpens       *ebpf.Map `ebpf:"pending_opens"`
	ProtectedDirs      *ebpf.Map `ebpf:"protected_dirs"`
	RingbufDrops       *ebpf.Map `ebpf:"ringbuf_drops"`
	ScratchEvents      *ebpf.Map `ebpf:"scratch_events"`
}

func (m *ransomwareUltraLegacyMaps) Close() error {
	return _RansomwareUltraLegacyClose(
		m.AllowedCgroups,
		m.BlockedTgids,
		m.CgroupScopeEnabled,
		m.EventCursor,
		m.Events,
		m.IocExtensions,
		m.IocRansomNotes,
		m.PendingOpens,
		m.ProtectedDirs,
		m.RingbufDrops,
		m.ScratchEvents,
	)
}

// ransomwareUltraLegacyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRansomwareUltraLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ransomwareUltraLegacyPrograms struct {
	KpOverrideExecve    *ebpf.Program `ebpf:"kp_override_execve"`
	KpOverrideFtruncate *ebpf.Program `ebpf:"kp_override_ftruncate"`
	KpOverrideLink      *ebpf.Program `ebpf:"kp_override_link"`
	KpOverrideOpen      *ebpf.Program `ebpf:"kp_override_open"`
	KpOverrideOpenat    *ebpf.Program `ebpf:"kp_override_openat"`
	KpOverridePwrite64  *ebpf.Program `ebpf:"kp_override_pwrite64"`
	KpOverrideRename    *ebpf.Program `ebpf:"kp_override_rename"`
	KpOverrideSymlink   *ebpf.Program `ebpf:"kp_override_symlink"`
	KpOverrideTruncate  *ebpf.Program `ebpf:"kp_override_truncate"`
	KpOverrideUnlink    *ebpf.Program `ebpf:"kp_override_unlink"`
	KpOverrideWrite     *ebpf.Program `ebpf:"kp_override_write"`
	KpOverrideWritev    *ebpf.Program `ebpf:"kp_override_writev"`
	KpRetOpen           *ebpf.Program `ebpf:"kp_ret_open"`
	KpRetOpenat         *ebpf.Program `ebpf:"kp_ret_openat"`
}

func (p *ransomwareUltraLegacyPrograms) Close() error {
	return _RansomwareUltraLegacyClose(
		p.KpOverrideExecve,
		p.KpOverrideFtruncate,
		p.KpOverrideLink,
		p.KpOverrideOpen,
		p.KpOverrideOpenat,
		p.KpOverridePwrite64,
		p.KpOverrideRename,
		p.KpOverrideSymlink,
		p.KpOverrideTruncate,
		p.KpOverrideUnlink,
		p.KpOverrideWrite,
		p.KpOverrideWritev,
		p.KpRetOpen,
		p.KpRetOpenat,
	)
}

func _RansomwareUltraLegacyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ransomwareultralegacy_bpfeb.o
var _RansomwareUltraLegacyBytes []byte
