// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRansomwareLegacy returns the embedded CollectionSpec for ransomwareLegacy.
func loadRansomwareLegacy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RansomwareLegacyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ransomwareLegacy: %w", err)
	}

	return spec, err
}

// loadRansomwareLegacyObjects loads ransomwareLegacy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ransomwareLegacyObjects
//	*ransomwareLegacyPrograms
//	*ransomwareLegacyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRansomwareLegacyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRansomwareLegacy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ransomwareLegacySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ransomwareLegacySpecs struct {
	ransomwareLegacyProgramSpecs
	ransomwareLegacyMapSpecs
}

// ransomwareLegacySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ransomwareLegacyProgramSpecs struct {
	KpOverrideCopyFileRange *ebpf.ProgramSpec `ebpf:"kp_override_copy_file_range"`
	KpOverrideExecve        *ebpf.ProgramSpec `ebpf:"kp_override_execve"`
	KpOverrideFtruncate     *ebpf.ProgramSpec `ebpf:"kp_override_ftruncate"`
	KpOverrideGetdents64    *ebpf.ProgramSpec `ebpf:"kp_override_getdents64"`
	KpOverrideIoUringEnter  *ebpf.ProgramSpec `ebpf:"kp_override_io_uring_enter"`
	KpOverrideLink          *ebpf.ProgramSpec `ebpf:"kp_override_link"`
	KpOverrideLinkat        *ebpf.ProgramSpec `ebpf:"kp_override_linkat"`
	KpOverrideMmap          *ebpf.ProgramSpec `ebpf:"kp_override_mmap"`
	KpOverrideOpenat        *ebpf.ProgramSpec `ebpf:"kp_override_openat"`
	KpOverrideOpenat2       *ebpf.ProgramSpec `ebpf:"kp_override_openat2"`
	KpOverridePwrite64      *ebpf.ProgramSpec `ebpf:"kp_override_pwrite64"`
	KpOverrideRename        *ebpf.ProgramSpec `ebpf:"kp_override_rename"`
	KpOverrideRenameat      *ebpf.ProgramSpec `ebpf:"kp_override_renameat"`
	KpOverrideRenameat2     *ebpf.ProgramSpec `ebpf:"kp_override_renameat2"`
	KpOverrideSymlink       *ebpf.ProgramSpec `ebpf:"kp_override_symlink"`
	KpOverrideSymlinkat     *ebpf.ProgramSpec `ebpf:"kp_override_symlinkat"`
	KpOverrideTruncate      *ebpf.ProgramSpec `ebpf:"kp_override_truncate"`
	KpOverrideUnlink        *ebpf.ProgramSpec `ebpf:"kp_override_unlink"`
	KpOverrideUnlinkat      *ebpf.ProgramSpec `ebpf:"kp_override_unlinkat"`
	KpOverrideWrite         *ebpf.ProgramSpec `ebpf:"kp_override_write"`
	KpOverrideWritev        *ebpf.ProgramSpec `ebpf:"kp_override_writev"`
	TraceClose              *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceConnect            *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceCopyFileRange      *ebpf.ProgramSpec `ebpf:"trace_copy_file_range"`
	TraceDup                *ebpf.ProgramSpec `ebpf:"trace_dup"`
	TraceDup2               *ebpf.ProgramSpec `ebpf:"trace_dup2"`
	TraceDup2Exit           *ebpf.ProgramSpec `ebpf:"trace_dup2_exit"`
	TraceDup3               *ebpf.ProgramSpec `ebpf:"trace_dup3"`
	TraceDup3Exit           *ebpf.ProgramSpec `ebpf:"trace_dup3_exit"`
	TraceDupExit            *ebpf.ProgramSpec `ebpf:"trace_dup_exit"`
	TraceExecve             *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceFcntl              *ebpf.ProgramSpec `ebpf:"trace_fcntl"`
	TraceFcntlExit          *ebpf.ProgramSpec `ebpf:"trace_fcntl_exit"`
	TraceFtruncate          *ebpf.ProgramSpec `ebpf:"trace_ftruncate"`
	TraceGetdents64         *ebpf.ProgramSpec `ebpf:"trace_getdents64"`
	TraceIoUringEnter       *ebpf.ProgramSpec `ebpf:"trace_io_uring_enter"`
	TraceLink               *ebpf.ProgramSpec `ebpf:"trace_link"`
	TraceLinkat             *ebpf.ProgramSpec `ebpf:"trace_linkat"`
	TraceMmap               *ebpf.ProgramSpec `ebpf:"trace_mmap"`
	TraceOpenat             *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceOpenat2            *ebpf.ProgramSpec `ebpf:"trace_openat2"`
	TraceOpenat2Exit        *ebpf.ProgramSpec `ebpf:"trace_openat2_exit"`
	TraceOpenatExit         *ebpf.ProgramSpec `ebpf:"trace_openat_exit"`
	TracePwrite64           *ebpf.ProgramSpec `ebpf:"trace_pwrite64"`
	TraceRename             *ebpf.ProgramSpec `ebpf:"trace_rename"`
	TraceRenameat           *ebpf.ProgramSpec `ebpf:"trace_renameat"`
	TraceRenameat2          *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceSymlink            *ebpf.ProgramSpec `ebpf:"trace_symlink"`
	TraceSymlinkat          *ebpf.ProgramSpec `ebpf:"trace_symlinkat"`
	TraceTruncate           *ebpf.ProgramSpec `ebpf:"trace_truncate"`
	TraceUnlink             *ebpf.ProgramSpec `ebpf:"trace_unlink"`
	TraceUnlinkat           *ebpf.ProgramSpec `ebpf:"trace_unlinkat"`
	TraceWrite              *ebpf.ProgramSpec `ebpf:"trace_write"`
	TraceWritev             *ebpf.ProgramSpec `ebpf:"trace_writev"`
}

// ransomwareLegacyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ransomwareLegacyMapSpecs struct {
	AllowedCgroups     *ebpf.MapSpec `ebpf:"allowed_cgroups"`
	BlockedTgids       *ebpf.MapSpec `ebpf:"blocked_tgids"`
	CgroupScopeEnabled *ebpf.MapSpec `ebpf:"cgroup_scope_enabled"`
	Events             *ebpf.MapSpec `ebpf:"events"`
	IocExtensions      *ebpf.MapSpec `ebpf:"ioc_extensions"`
	IocRansomNotes     *ebpf.MapSpec `ebpf:"ioc_ransom_notes"`
	PendingDups        *ebpf.MapSpec `ebpf:"pending_dups"`
	PendingOpens       *ebpf.MapSpec `ebpf:"pending_opens"`
	ProtectedDirs      *ebpf.MapSpec `ebpf:"protected_dirs"`
	RingbufDrops       *ebpf.MapSpec `ebpf:"ringbuf_drops"`
	ScratchEvents      *ebpf.MapSpec `ebpf:"scratch_events"`
}

// ransomwareLegacyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRansomwareLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ransomwareLegacyObjects struct {
	ransomwareLegacyPrograms
	ransomwareLegacyMaps
}

func (o *ransomwareLegacyObjects) Close() error {
	return _RansomwareLegacyClose(
		&o.ransomwareLegacyPrograms,
		&o.ransomwareLegacyMaps,
	)
}

// ransomwareLegacyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRansomwareLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ransomwareLegacyMaps struct {
	AllowedCgroups     *ebpf.Map `ebpf:"allowed_cgroups"`
	BlockedTgids       *ebpf.Map `ebpf:"blocked_tgids"`
	CgroupScopeEnabled *ebpf.Map `ebpf:"cgroup_scope_enabled"`
	Events             *ebpf.Map `ebpf:"events"`
	IocExtensions      *ebpf.Map `ebpf:"ioc_extensions"`
	IocRansomNotes     *ebpf.Map `ebpf:"ioc_ransom_notes"`
	PendingDups        *ebpf.Map `ebpf:"pending_dups"`
	PendingOpens       *ebpf.Map `ebpf:"pending_opens"`
	ProtectedDirs      *ebpf.Map `ebpf:"protected_dirs"`
	RingbufDrops       *ebpf.Map `ebpf:"ringbuf_drops"`
	ScratchEvents      *ebpf.Map `ebpf:"scratch_events"`
}

func (m *ransomwareLegacyMaps) Close() error {
	return _RansomwareLegacyClose(
		m.AllowedCgroups,
		m.BlockedTgids,
		m.CgroupScopeEnabled,
		m.Events,
		m.IocExtensions,
		m.IocRansomNotes,
		m.PendingDups,
		m.PendingOpens,
		m.ProtectedDirs,
		m.RingbufDrops,
		m.ScratchEvents,
	)
}

// ransomwareLegacyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRansomwareLegacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ransomwareLegacyPrograms struct {
	KpOverrideCopyFileRange *ebpf.Program `ebpf:"kp_override_copy_file_range"`
	KpOverrideExecve        *ebpf.Program `ebpf:"kp_override_execve"`
	KpOverrideFtruncate     *ebpf.Program `ebpf:"kp_override_ftruncate"`
	KpOverrideGetdents64    *ebpf.Program `ebpf:"kp_override_getdents64"`
	KpOverrideIoUringEnter  *ebpf.Program `ebpf:"kp_override_io_uring_enter"`
	KpOverrideLink          *ebpf.Program `ebpf:"kp_override_link"`
	KpOverrideLinkat        *ebpf.Program `ebpf:"kp_override_linkat"`
	KpOverrideMmap          *ebpf.Program `ebpf:"kp_override_mmap"`
	KpOverrideOpenat        *ebpf.Program `ebpf:"kp_override_openat"`
	KpOverrideOpenat2       *ebpf.Program `ebpf:"kp_override_openat2"`
	KpOverridePwrite64      *ebpf.Program `ebpf:"kp_override_pwrite64"`
	KpOverrideRename        *ebpf.Program `ebpf:"kp_override_rename"`
	KpOverrideRenameat      *ebpf.Program `ebpf:"kp_override_renameat"`
	KpOverrideRenameat2     *ebpf.Program `ebpf:"kp_override_renameat2"`
	KpOverrideSymlink       *ebpf.Program `ebpf:"kp_override_symlink"`
	KpOverrideSymlinkat     *ebpf.Program `ebpf:"kp_override_symlinkat"`
	KpOverrideTruncate      *ebpf.Program `ebpf:"kp_override_truncate"`
	KpOverrideUnlink        *ebpf.Program `ebpf:"kp_override_unlink"`
	KpOverrideUnlinkat      *ebpf.Program `ebpf:"kp_override_unlinkat"`
	KpOverrideWrite         *ebpf.Program `ebpf:"kp_override_write"`
	KpOverrideWritev        *ebpf.Program `ebpf:"kp_override_writev"`
	TraceClose              *ebpf.Program `ebpf:"trace_close"`
	TraceConnect            *ebpf.Program `ebpf:"trace_connect"`
	TraceCopyFileRange      *ebpf.Program `ebpf:"trace_copy_file_range"`
	TraceDup                *ebpf.Program `ebpf:"trace_dup"`
	TraceDup2               *ebpf.Program `ebpf:"trace_dup2"`
	TraceDup2Exit           *ebpf.Program `ebpf:"trace_dup2_exit"`
	TraceDup3               *ebpf.Program `ebpf:"trace_dup3"`
	TraceDup3Exit           *ebpf.Program `ebpf:"trace_dup3_exit"`
	TraceDupExit            *ebpf.Program `ebpf:"trace_dup_exit"`
	TraceExecve             *ebpf.Program `ebpf:"trace_execve"`
	TraceFcntl              *ebpf.Program `ebpf:"trace_fcntl"`
	TraceFcntlExit          *ebpf.Program `ebpf:"trace_fcntl_exit"`
	TraceFtruncate          *ebpf.Program `ebpf:"trace_ftruncate"`
	TraceGetdents64         *ebpf.Program `ebpf:"trace_getdents64"`
	TraceIoUringEnter       *ebpf.Program `ebpf:"trace_io_uring_enter"`
	TraceLink               *ebpf.Program `ebpf:"trace_link"`
	TraceLinkat             *ebpf.Program `ebpf:"trace_linkat"`
	TraceMmap               *ebpf.Program `ebpf:"trace_mmap"`
	TraceOpenat             *ebpf.Program `ebpf:"trace_openat"`
	TraceOpenat2            *ebpf.Program `ebpf:"trace_openat2"`
	TraceOpenat2Exit        *ebpf.Program `ebpf:"trace_openat2_exit"`
	TraceOpenatExit         *ebpf.Program `ebpf:"trace_openat_exit"`
	TracePwrite64           *ebpf.Program `ebpf:"trace_pwrite64"`
	TraceRename             *ebpf.Program `ebpf:"trace_rename"`
	TraceRenameat           *ebpf.Program `ebpf:"trace_renameat"`
	TraceRenameat2          *ebpf.Program `ebpf:"trace_renameat2"`
	TraceSymlink            *ebpf.Program `ebpf:"trace_symlink"`
	TraceSymlinkat          *ebpf.Program `ebpf:"trace_symlinkat"`
	TraceTruncate           *ebpf.Program `ebpf:"trace_truncate"`
	TraceUnlink             *ebpf.Program `ebpf:"trace_unlink"`
	TraceUnlinkat           *ebpf.Program `ebpf:"trace_unlinkat"`
	TraceWrite              *ebpf.Program `ebpf:"trace_write"`
	TraceWritev             *ebpf.Program `ebpf:"trace_writev"`
}

func (p *ransomwareLegacyPrograms) Close() error {
	return _RansomwareLegacyClose(
		p.KpOverrideCopyFileRange,
		p.KpOverrideExecve,
		p.KpOverrideFtruncate,
		p.KpOverrideGetdents64,
		p.KpOverrideIoUringEnter,
		p.KpOverrideLink,
		p.KpOverrideLinkat,
		p.KpOverrideMmap,
		p.KpOverrideOpenat,
		p.KpOverrideOpenat2,
		p.KpOverridePwrite64,
		p.KpOverrideRename,
		p.KpOverrideRenameat,
		p.KpOverrideRenameat2,
		p.KpOverrideSymlink,
		p.KpOverrideSymlinkat,
		p.KpOverrideTruncate,
		p.KpOverrideUnlink,
		p.KpOverrideUnlinkat,
		p.KpOverrideWrite,
		p.KpOverrideWritev,
		p.TraceClose,
		p.TraceConnect,
		p.TraceCopyFileRange,
		p.TraceDup,
		p.TraceDup2,
		p.TraceDup2Exit,
		p.TraceDup3,
		p.TraceDup3Exit,
		p.TraceDupExit,
		p.TraceExecve,
		p.TraceFcntl,
		p.TraceFcntlExit,
		p.TraceFtruncate,
		p.TraceGetdents64,
		p.TraceIoUringEnter,
		p.TraceLink,
		p.TraceLinkat,
		p.TraceMmap,
		p.TraceOpenat,
		p.TraceOpenat2,
		p.TraceOpenat2Exit,
		p.TraceOpenatExit,
		p.TracePwrite64,
		p.TraceRename,
		p.TraceRenameat,
		p.TraceRenameat2,
		p.TraceSymlink,
		p.TraceSymlinkat,
		p.TraceTruncate,
		p.TraceUnlink,
		p.TraceUnlinkat,
		p.TraceWrite,
		p.TraceWritev,
	)
}

func _RansomwareLegacyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ransomwarelegacy_bpfel.o
var _RansomwareLegacyBytes []byte
